// Problem 12
//The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//Let us list the factors of the first seven triangle numbers:
//1: 1
//3: 1, 3
//6: 1, 2, 3, 6
//10: 1, 2, 5, 10
//15: 1, 3, 5, 15
//21: 1, 3, 7, 21
//28: 1, 2, 4, 7, 14, 28
//We can see that 28 is the first triangle number to have over five divisors.
//What is the value of the first triangle number to have over five hundred divisors?
function triangleNumber(n) {
    var result = 0;
    for (var i = 0; i <= n; i++) {
        result += i;
    }
    return result;
}
function getDivisors(n) {
    var divisors = [];
    var upper = Math.floor(n / 2);
    divisors.push(1);
    for (var i = 2; i <= upper; i++) {
        if (n % i === 0)
            divisors.push(i);
    }
    divisors.push(n);
    return divisors;
}
function Problem12() {
    var divisors = [];
    var n = 0;
    var triangleNum = 0;
    do {
        n++;
        triangleNum = triangleNumber(n);
        divisors = getDivisors(triangleNum);
    } while (divisors.length < 501);
    console.log(divisors);
    console.log(triangleNum);
}
//# sourceMappingURL=Problem12.js.map