//// Problem 2:
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even- valued terms.
function fib(n) {
    if (n <= 2) {
        return 1;
    }
    else {
        return this.fib(n - 1) + this.fib(n - 2);
    }
}
function Problem2() {
    var result = 0;
    var counter = 1;
    var sum = 0;
    do {
        result = fib(counter);
        if (result % 2 == 0)
            sum += result;
        counter++;
    } while (result < 4000000);
    console.log(sum);
}
//# sourceMappingURL=Problem2.js.map